### ISSUE TITLE
Your CloudFormation for Cloud9 env does not work

### ISSUE THREAD

**Issue by AWS-Organization-Admin** [aws-samples/one-observability-demo#109]
Please take a look at your cloud formation yaml.  it does not work.
I got a roll-back as your Cloudformation tried to crate resources.

curl -O https://raw.githubusercontent.com/aws-samples/one-observability-demo/main/cloud9-cfn.yaml

aws cloudformation create-stack --stack-name C9-Observability-Workshop --template-body file://cloud9-cfn.yaml --capabilities CAPABILITY_NAMED_IAM

**Comment by awsimaya** [comment]
What error did you get? Cannot reproduce the error. Can you paste the error details?

**Comment by awsimaya** [comment]
Closing this issue as there is no response.
