### ISSUE TITLE
Could not start a Cloud9 environment from CloudShell (EventEngine account)

### ISSUE THREAD

**Issue by giusedroid** [aws-samples/one-observability-demo#113]
Hi all,  
I had an issue creating the Cloud9 environment from an account created via event engine.  
The event engine account was bootstrapped with the default template.  
Here's the error I got

```
Unable to start the environment. You don't have required permissions. Ask your IAM administrator for access to AWS CloudShell. System error: User: arn:aws:sts:::assumed-role/TeamRole/MasterKey is not authorized to perform: cloudshell:CreateEnvironment on resource: arn:aws:cloudshell:eu-west-1::* with an explicit deny
```

Is it mandatory to set up the account with the workshop blueprint or is it possible to manually bootstrap it later?

**Comment by awsimaya** [comment]
Pleas do not use the default blueprint. Use the one suggested in the guide.
