### ISSUE TITLE
 C9-Observability-Workshop template error

### ISSUE THREAD

**Issue by AWS-Organization-Admin** [aws-samples/one-observability-demo#114]
I tried to launch the C9-Observability-Workshop using **cloud9-cfn.yaml** template and it keeps role back.
Thanks
John Nguyen

**Comment by nzoueidi** [comment]
Could you please elaborate and give more information and how the CFN template failed?

**Comment by awsimaya** [comment]
Closing this issue as there is no response.

**Comment by davecloudguy** [comment]
I'd like to reopen this one.

I launch the CloudFormation template, it mostly launches, then this error after the 1 hour wait had expired:

2023-10-18 15:46:01 UTC-0400 | BootstrapWaitCondition | CREATE_FAILED | WaitCondition timed out. Received 0 conditions when expecting 1
-- | -- | -- | --

When I run  cfn-lint: I get the following against the template, I get:

cfn-lint cloud9-cfn.yaml
W2506 Parameter C9Image should be of type [AWS::EC2::Image::Id, AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>]
cloud9-cfn.yaml:68:3

So, I set  the C9Image to be:

  C9Image:
    Type: AWS::EC2::Image::Id
    Description: The Image to use for the Cloud9Instance
    Default:  ami-0fc5d935ebf8bc3bc

No errors on the cfn-lint, however, it won't launch at all, the error I receive is:

Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: Matched expected service error code: ValidationError

Thanks.

**Comment by awsimaya** [comment]
@rafaelpereyra , can you look into this?
