### ISSUE TITLE
ERROR DURING DEPLOY STACK SERVICES

### ISSUE THREAD

**Issue by ftrimoldi** [aws-samples/one-observability-demo#120]
With The following step of deploy Services:

**cdk deploy --context admin_role=$EKS_ADMIN_ARN Services --context dashboard_role_arn=$CONSOLE_ROLE_ARN --require-approval never**

I'getting the following error:

**User: arn:aws:sts::307496335113:assumed-role/observabilityworkshop-admin/i-0b798ba3b2fdce063 is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-south-1:580247275435:layer:LambdaInsightsExtension:2 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: d703fbe5-e64f-4df7-94d0-2c59afb32741; Proxy: null)**

and then it rollabacks.

My EKS_ADMIN_ARN=arn:aws:iam::307496335113:role/observabilityworkshop-admin 

and it's validated

and my CONSOLE_ROLE_ARN=arn:aws:iam::307496335113:user/fabrizio.trimoldi@S2E-Pro.com

I tried unsetting CONSOLE_ROLE_ARN too and executed the following step below

cdk deploy --context admin_role=$EKS_ADMIN_ARN Services

but I got the same error, can you tell me what's happening ? Thanks

**Comment by awsimaya** [comment]
Looks like you don't have the required permissions to deploy. Can you try in an account with admin permissions?
