### ISSUE TITLE
Documentation about the pricing

### ISSUE THREAD

**Issue by fabientownsend** [aws-samples/one-observability-demo#121]
I know that there is a bit about the pricing but I think it would be good to add a rough estimation of the cost based on time. 😄 

I have been a bit naive and let it run which cost me $30 😨 . It's quite hard to tell for how long it ran as the first time I ran the environment cleanup it didn't removes everything but it must be between 10/20 hours. It would be good to also add in the section "Environment cleanup" how to manually check that things a properly deleted 💯

**Comment by awsimaya** [comment]
It's really difficult to come up with an estimate. While we will certainly try if we can find a way to do that, this is why we have this point called out in the home page and ask the user to cleanup the resources after usage.
