### ISSUE TITLE
The Clean Up Script is not working

### ISSUE THREAD

**Issue by rmmathik** [aws-samples/one-observability-demo#125]
Hi Team,

The Clean Up Script is not working. Kindly help as it is consuming a lot of resources. 

The Error message when we execute the command "curl https://raw.githubusercontent.com/aws-samples/one-observability-demo/main/PetAdoptions/cdk/pet_stack/resources/destroy_stack.sh | bash" is as follows.

STARTING SERVICES CLEANUP
-----------------------------
Added new context arn:aws:eks:us-east-2:908546734614:cluster/PetSite to /home/ec2-user/.kube/config
error: the path "./resources/load_balancer/crds.yaml" does not exist

**Comment by nzoueidi** [comment]
You should execute the curl command from the appropriate path: https://github.com/aws-samples/one-observability-demo/tree/main/PetAdoptions/cdk/pet_stack

The crds.yaml file does not exist in your current path. Ensure that you are in one-observability-demo/PetAdoptions/cdk/pet_stack/
