### ISSUE TITLE
Inconsistencies experienced during workshop using own account.

### ISSUE THREAD

**Issue by matthew-dawson** [aws-samples/one-observability-demo#135]
Having completed the workshop (twice, with the second attempt confirming initial results), there seems to be two  inconsistencies between the expected results presented within the documentation and actual results generated within our environment. 

1. The Kubernetes cluster monitoring (via Prometheus) dashboard does not display the cluster level hardware resources as expected.  The Total usage group, consisting of Cluster memory usage, Cluster CPU usage (2m avg), and Cluster filesystem usage panes are all unable to display metrics for Total (returning N/A), thus the gauge panes associated are also returning N/A.
![Screenshot 2021-07-15 at 17 05 55](https://user-images.githubusercontent.com/4986903/125820522-4ab33061-56b3-4588-b557-1cc11d203a93.png)

This behaviour is experienced in both the self-managed Grafana deployment onto the EKS cluster (Exercise 15.4 - step 12, Query Metrics) as well as the managed AMG deployment (Exercise 16.2, step 7).

2. Clicking on the Trace IDs within the X-Ray Query results within AMP (Exercise 16 - Step 9) returns a "Bad Request: Invalid URI" error rather than presenting the expected stack trace.

The workshop documentation used for this exercise is found at - https://observability.workshop.aws/en/intro.html

**Comment by awsimaya** [comment]
This is due to the dashboard queries changing. Some of the metrics have been changed that what you find in the Grafana dashboard that we are importing from Grafana Dashboards (which is crowd sourced). Changing the metric names and filtering them using appropriate label values fixes this.
