### ISSUE TITLE
Increasing Cloud9 disk size to 30GB 

### ISSUE THREAD

**Issue by comeddy** [aws-samples/one-observability-demo#136]
<pre>
pip3 install --user --upgrade boto3
export instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
python -c "import boto3
import os
from botocore.exceptions import ClientError 
ec2 = boto3.client('ec2')
volume_info = ec2.describe_volumes(
    Filters=[
        {
            'Name': 'attachment.instance-id',
            'Values': [
                os.getenv('instance_id')
            ]
        }
    ]
)
volume_id = volume_info['Volumes'][0]['VolumeId']
try:
    resize = ec2.modify_volume(    
            VolumeId=volume_id,    
            Size=30
    )
    print(resize)
except ClientError as e:
    if e.response['Error']['Code'] == 'InvalidParameterValue':
        print('ERROR MESSAGE: {}'.format(e))"
if [ $? -eq 0 ]; then
    sudo reboot
fi
</pre>

**Comment by comeddy** [comment]
It need to be increasing Cloud9 disk size up to 30GB before CDK bootstrap install

**Comment by awsimaya** [comment]
Not sure what the Issue is. The script we have on the workshop will resize the storage to 30GB. If that did not work, please raise the issue again.
