### ISSUE TITLE
cdk deploy Applications stack is failing

### ISSUE THREAD

**Issue by edwio** [aws-samples/one-observability-demo#153]
Its seems that there is some problem with the deploying of the Application stack, using the cdk:

`2021-12-12 17:48:44 UTC+0200 | Applications | ROLLBACK_IN_PROGRESS | The following resource(s) failed to create: [petsitedeployment6E1B5498]. Rollback requested by user.`

`2021-12-12 17:48:43 UTC+0200 | petsitedeployment6E1B5498 | CREATE_FAILED | Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": serviceaccounts "petsite-sa" already exists\nError from server (Invalid): error when creating "/tmp/manifest.yaml": Service "service-petsite" is invalid: spec.ports[0].nodePort: Invalid value: 30300: provided port is already allocated\nError from server (AlreadyExists): error when creating "/tmp/manifest.yaml": deployments.apps "petsite-deployment" already exists\nError from server (TargetGroup arn:aws:elasticloadbalancing:eu-west-1:443682937418:targetgroup/Servi-PetSi-X6EIRRTLSMPM/e16b09093677626c is already bound to TargetGroupBinding default/petsite-tgb): error when creating "/tmp/manifest.yaml": admission webhook "vtargetgroupbinding.elbv2.k8s.aws" denied the request: TargetGroup arn:aws:elasticloadbalancing:eu-west-1:443682937418:targetgroup/Servi-PetSi-X6EIRRTLSMPM/e16b09093677626c is already bound to TargetGroupBinding default/petsite-tgb\n' Logs: /aws/lambda/Applications-ApplicationsMyCluster-Handler886CB40B-3BBmNGYJ2tGl at invokeUserFunction (/var/task/framework.js:95:19) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async onEvent (/var/task/framework.js:19:27) at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: 3ed8d041-e09b-441a-9078-8c52b51820e9)`

![image](https://user-images.githubusercontent.com/50066745/145719385-d1dcae0b-e328-4772-a1d4-a98a664da0fa.png)
![image](https://user-images.githubusercontent.com/50066745/145719406-e3a75310-2094-4d98-b106-b8ba4350ebe5.png)

**Comment by Arctos999** [comment]
I am having the same issue when I try to run the lab.  The events/errors I am getting are the same as edwio has copied in the original issue description.

**Comment by awsimaya** [comment]
There was a race condition which was fixed already.
