### ISSUE TITLE
Issues with AWS CloudTrail Log Monitoring Workshop

### ISSUE THREAD

**Issue by JaspalJC** [aws-samples/one-observability-demo#159]
Hi Team,

In the aforementioned workshop, to set up your own personal environment (https://catalog.us-east-1.prod.workshops.aws/v2/workshops/2e48b9fc-f721-4417-b811-962b7f31b61c/en-US/installation/not-using-ee/setup-cloud9) refers to a step:
curl -O https://raw.githubusercontent.com/awstiber/cloudwatch-logs-code/main/cloud9-cfn.yaml
But the yaml file is not available at the location (404: Not Found error).
Please fix and confirm back once done.
Thanks,
Jaspal Singh | e: Jaspal@Singh.name

**Comment by awsimaya** [comment]
This repo is not related to the workshop you mentioned. Closing this issue.
