### ISSUE TITLE
Canary do not work on Event Engine

### ISSUE THREAD

**Issue by felipebortto** [aws-samples/one-observability-demo#34]
Hi, 
When  we try to create the cloudwatch canary the Event Engine account do not permit its creation

Error:
User: arn:aws:sts::084095818662:assumed-role/TeamRole/MasterKey is not authorized to perform: synthetics:DescribeCanaries on resource: arn:aws:synthetics:us-east-1:084095818662:canary:* with an explicit deny

Thanks

**Comment by awsimaya** [comment]
Known issue. We are working internally to fix address this.
