### ISSUE TITLE
Two Cloud9 IDEs can be created when not using Custom Event Engine Template

### ISSUE THREAD

**Issue by alahser** [aws-samples/one-observability-demo#37]
So, if you are setting this up in a regular (non-event engine account), you create a Cloud9 environment, then run these commands

```
curl -O https://raw.githubusercontent.com/aws-samples/one-observability-demo/main/cloud9-cfn.yaml

aws cloudformation create-stack --stack-name C9-Observability-Workshop --template-body file://cloud9-cfn.yaml --capabilities CAPABILITY_NAMED_IAM
```

I believe these commands setup another Cloud9 IDE.  I took a screenshot
<img width="764" alt="Screen Shot 2020-11-10 at 6 04 59 PM" src="https://user-images.githubusercontent.com/5279443/98744313-7d017b80-237f-11eb-993f-8e9d7849f56b.png">

When you finally get here: 

```
test -n "$AWS_REGION" && echo AWS_REGION is "$AWS_REGION" || echo AWS_REGION is not set

aws sts get-caller-identity --query Arn | grep observabilityworkshop-admin -q && echo "You're good. IAM role IS valid." || echo "IAM role NOT valid. DO NOT PROCEED."

```

You get an IAM role error. See another screenshot

<img width="1029" alt="Screen Shot 2020-11-10 at 6 07 39 PM" src="https://user-images.githubusercontent.com/5279443/98744401-a4f0df00-237f-11eb-9c8a-7f25f53ed6b5.png">

At this point, if you return to the Cloud9 selection, you see that a 2nd environment is there. If you enter that Cloud9 and repeat all the steps, you can get past the IAM role error. 

Having watched customers struggle with the deployment, I strongly suggest separate pages for each kind of deployment (Event Engine, Standalone, and non-using Cloud9). Many of them were executing commands blindly (rebooting, etc) without reading fully.

**Comment by awsimaya** [comment]
The workshop *only* works with custom EE blueprint or using own AWS account with proper perms.  In this case it seems the custom blueprint was not used, which is a scenario the workshop doesn't support. Please reach out and to get access to the blueprint.
