### ISSUE TITLE
Alarm notification does not work on Event Engine

### ISSUE THREAD

**Issue by yehjxraymond** [aws-samples/one-observability-demo#45]
When creating an alarm notification it throws the following error:

![image](https://user-images.githubusercontent.com/7406870/102191530-81780180-3ef4-11eb-98d1-dd9ac8b0759f.png)

Seemed like the account does not have access to SNS. Current workaround during the workshop is to create the alarm without notification.

**Comment by awsimaya** [comment]
Fixed already.
